services:
  - type: web
    name: aicapstone
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port 8000
    plan: free  # Explicitly set to free tier
 
    buildCommand: |
      pip install -r requirements.txt        # Install dependencies
 
    startCommand: |
      python api.py                          # Command to start FastAPI application
 
    envVars:                                 # Environment variables for the service
      - key: CHROMA_DB_PATH                  # Path for persistent ChromaDB storage
        value: /opt/render/chroma_db
      - key: PYTHON_VERSION                  # Ensure Python version matches your local dev environment
        value: 3.10
 
    disk:                                    # Persistent storage for ChromaDB (for saving vectors)
      - name: chromadb-storage
        mountPath: /opt/render/chroma_db     # Ensure ChromaDB storage persists across restarts
        sizeGB: 1                             # Minimum 1GB for vector storage
 
    healthCheckPath: /search                 # FastAPI endpoint to monitor service health
    autoDeploy: true                         # Automatically deploy new commits
